version: '3'
services: 
   mysql:
      image: mysql:8
      restart: always
      command: --default-authentication-plugin=mysql_native_password 
      environment:
         MYSQL_DATABASE: 'kek'
         # So you don't have to use root, but you can if you like
         MYSQL_USER: 'user'
         # You can use whatever password you like
         MYSQL_PASSWORD: 'admin'
         # Password for root access
         MYSQL_ROOT_PASSWORD: 'admin'
      ports:
      - 3307:3306
      expose:
      - 3307
   app:
      build: ./API
      container_name: inventory-API
      expose: 
      - 80
      depends_on: 
      - "mysql"
      ports:
      - 80:3000
      links:
		- mysql

