version: '3'
services: 
   mysql:
      image: mysql:8
      restart: always
      command: --default-authentication-plugin=mysql_native_password 
      environment:
         MYSQL_DATABASE: 'kek'
         # So you don't have to use root, but you can if you like
         MYSQL_USER: 'user'
         # You can use whatever password you like
         MYSQL_PASSWORD: 'admin'
         # Password for root access
         MYSQL_ROOT_PASSWORD: 'admin'
      ports:
      - 3307:3306
      expose:
      - 3307
   app:
      build: ./API
      container_name: inventory-API
      expose: 
      - 3000
      - ${API_PORT}
      environment:
      - NODE_ENV=${NODE_ENV}
      - HOST=${HOST}
      - JWT_TOKEN=${JWT_TOKEN}
      - API_PORT=${API_PORT}
      depends_on: 
      - "mysql"
      ports:
      - ${API_PORT}:${API_PORT}
      links:
      - mysql
      
   client:
      build: 
         context: ./frontend
         args: 
            API_PORT: ${API_PORT}
      container_name: apache-client
      environment:
         - NODE_ENV=${NODE_ENV}
         - HOST=${HOST}
         - JWT_TOKEN=${JWT_TOKEN}
         - API_PORT=${API_PORT}
      expose:
      - 80
      ports:
      - 80:80
      links: 
      - app
